//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task4Database.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task4Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id;Name
        ///1;Юдин Адам
        ///2;Яшина Яна
        ///3;Никитина Вероника
        ///4;Рябинин Александр
        ///5;Ильин Тимофей
        ///6;Кулагина Виктория
        ///7;Лапшина Варвара
        ///8;Лопатина Камилла
        ///9;Кузьмина Елизавета
        ///10;Галкина Есения
        ///11;Панина Таисия
        ///12;Семина Арина
        ///13;Бабушкин Иван
        ///14;Кузьмин Глеб
        ///15;Добрынин Степан
        ///16;Фомин Никита
        ///17;Маркина Кристина
        ///18;Зеленина Кира
        ///19;Капустина Елизавета
        ///20;Костин Александр
        ///.
        /// </summary>
        internal static string Juniors20 {
            get {
                return ResourceManager.GetString("Juniors20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id;Name
        ///1;Филиппова Ульяна
        ///2;Николаев Григорий
        ///3;Андреева Вероника
        ///4;Коротков Михаил
        ///5;Кузнецов Александр
        ///6;Максимов Иван
        ///7;Павлова Мария
        ///8;Артемов Матвей
        ///9;Денисов Дмитрий
        ///10;Астафьев Андрей
        ///11;Демидов Дмитрий
        ///12;Климов Михаил
        ///13;Терехов Демид
        ///14;Полякова Мария
        ///15;Волков Мирослав
        ///16;Волкова Ольга
        ///17;Киреева Виктория
        ///18;Волков Артём
        ///19;Панов Максим
        ///20;Комаров Макар
        ///.
        /// </summary>
        internal static string Teamleads20 {
            get {
                return ResourceManager.GetString("Teamleads20", resourceCulture);
            }
        }
    }
}
