// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task5Http.Database;

#nullable disable

namespace Task5Http.Migrations
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20241119123128_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Task4Database.Data.Entity.Hackaton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Harmony")
                        .HasColumnType("REAL")
                        .HasColumnName("harmony");

                    b.HasKey("Id");

                    b.ToTable("hackaton", (string)null);
                });

            modelBuilder.Entity("Task4Database.Data.Entity.Junior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("junior", (string)null);
                });

            modelBuilder.Entity("Task4Database.Data.Entity.JuniorPreference", b =>
                {
                    b.Property<int>("HackatonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hackaton_id");

                    b.Property<int>("JuniorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("junior_id");

                    b.Property<int>("TeamleadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamlead_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.HasKey("HackatonId", "JuniorId", "TeamleadId");

                    b.HasIndex("JuniorId");

                    b.HasIndex("TeamleadId");

                    b.ToTable("junior_preference", (string)null);
                });

            modelBuilder.Entity("Task4Database.Data.Entity.Team", b =>
                {
                    b.Property<int>("HackatonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hackaton_id");

                    b.Property<int>("JuniorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("junior_id");

                    b.Property<int>("TeamleadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamlead_id");

                    b.HasKey("HackatonId", "JuniorId", "TeamleadId");

                    b.HasIndex("JuniorId");

                    b.HasIndex("TeamleadId");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("Task4Database.Data.Entity.Teamlead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("teamlead", (string)null);
                });

            modelBuilder.Entity("Task4Database.Data.Entity.TeamleadPreference", b =>
                {
                    b.Property<int>("HackatonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hackaton_id");

                    b.Property<int>("JuniorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("junior_id");

                    b.Property<int>("TeamleadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamlead_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.HasKey("HackatonId", "JuniorId", "TeamleadId");

                    b.HasIndex("JuniorId");

                    b.HasIndex("TeamleadId");

                    b.ToTable("teamlead_preference", (string)null);
                });

            modelBuilder.Entity("Task4Database.Data.Entity.JuniorPreference", b =>
                {
                    b.HasOne("Task4Database.Data.Entity.Hackaton", "Hackaton")
                        .WithMany()
                        .HasForeignKey("HackatonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task4Database.Data.Entity.Junior", "Junior")
                        .WithMany()
                        .HasForeignKey("JuniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task4Database.Data.Entity.Teamlead", "PreferredTeamlead")
                        .WithMany()
                        .HasForeignKey("TeamleadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hackaton");

                    b.Navigation("Junior");

                    b.Navigation("PreferredTeamlead");
                });

            modelBuilder.Entity("Task4Database.Data.Entity.Team", b =>
                {
                    b.HasOne("Task4Database.Data.Entity.Hackaton", "Hackaton")
                        .WithMany("Teams")
                        .HasForeignKey("HackatonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task4Database.Data.Entity.Junior", "Junior")
                        .WithMany()
                        .HasForeignKey("JuniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task4Database.Data.Entity.Teamlead", "Teamlead")
                        .WithMany()
                        .HasForeignKey("TeamleadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hackaton");

                    b.Navigation("Junior");

                    b.Navigation("Teamlead");
                });

            modelBuilder.Entity("Task4Database.Data.Entity.TeamleadPreference", b =>
                {
                    b.HasOne("Task4Database.Data.Entity.Hackaton", "Hackaton")
                        .WithMany()
                        .HasForeignKey("HackatonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task4Database.Data.Entity.Junior", "PreferredJunior")
                        .WithMany()
                        .HasForeignKey("JuniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task4Database.Data.Entity.Teamlead", "Teamlead")
                        .WithMany()
                        .HasForeignKey("TeamleadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hackaton");

                    b.Navigation("PreferredJunior");

                    b.Navigation("Teamlead");
                });

            modelBuilder.Entity("Task4Database.Data.Entity.Hackaton", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
